# Generated by Django 5.2.13 on 2026-04-15 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset_name', models.CharField(default='youtube_1080p', help_text='Label only — render settings live in the engine preset.', max_length=48)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('output_path', models.CharField(blank=True, default='', help_text="Path relative to KINORO_RENDER_DIR (e.g. '<uuid>.mp4').", max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
