# Generated by Django 5.2.13 on 2026-04-14 23:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('fps', models.PositiveIntegerField(default=30)),
                ('width', models.PositiveIntegerField(default=1920)),
                ('height', models.PositiveIntegerField(default=1080)),
                ('timeline_json', models.JSONField(blank=True, default=dict)),
                ('render_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
