# Generated by Django 5.2.13 on 2026-04-14 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField(default='https://api.videoplanner.io', help_text='Video Planner base URL, e.g. https://api.videoplanner.io')),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user_payload', models.JSONField(blank=True, default=dict, help_text='The `user` object returned by /api/auth/login/ — name, avatar, plan.')),
            ],
            options={
                'verbose_name': 'Video Planner account',
            },
        ),
        migrations.CreateModel(
            name='VPImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('api', 'Live API'), ('zip', 'ZIP file')], max_length=10)),
                ('remote_project_id', models.CharField(blank=True, default='', max_length=64)),
                ('zip_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetching_project', 'Fetching project'), ('downloading_media', 'Downloading media'), ('building_proxies', 'Building proxies'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('progress', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('kinoro_project_id', models.CharField(blank=True, default='', help_text='Populated once the Kinoro-side Project row is created.', max_length=64)),
                ('account', models.ForeignKey(blank=True, help_text='Null for zip-based imports (no account required).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='import_vp.vpaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
