# Generated by Django 5.2.13 on 2026-04-14 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('source_path', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('status', models.CharField(choices=[('ingesting', 'Ingesting'), ('ready', 'Ready'), ('failed', 'Failed')], default='ingesting', max_length=10)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('probe_json', models.JSONField(blank=True, default=dict)),
                ('thumbnail_path', models.CharField(blank=True, default='', help_text="Path relative to MEDIA_ROOT (e.g. 'thumbnails/<uuid>.jpg').", max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
