# Generated by Django 5.2.13 on 2026-04-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='vp_asset_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='VP vediteur MediaAsset id or Resource id this row was imported from.', max_length=64),
        ),
    ]
