# Generated by Django 5.2.13 on 2026-04-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediaasset_vp_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='proxy_path',
            field=models.CharField(blank=True, default='', help_text="Path relative to KINORO_PROXY_DIR (e.g. '<uuid>.mp4').", max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='proxy_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12),
        ),
    ]
